// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmR_mIE36h9234f3THq2ygPWn34_hDahc',
    appId: '1:32563411035:web:9af7bad9052f25efbaa77e',
    messagingSenderId: '32563411035',
    projectId: 'practice1auth',
    authDomain: 'practice1auth.firebaseapp.com',
    storageBucket: 'practice1auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRYkLS0Q0cs0lM2amJzsknWX7AhKpWHog',
    appId: '1:32563411035:android:82b702ed563b990cbaa77e',
    messagingSenderId: '32563411035',
    projectId: 'practice1auth',
    storageBucket: 'practice1auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgb7i5_rGY4EK8U5a_843vD3qedBQvrw',
    appId: '1:32563411035:ios:d285cbaa09c82b06baa77e',
    messagingSenderId: '32563411035',
    projectId: 'practice1auth',
    storageBucket: 'practice1auth.appspot.com',
    iosBundleId: 'com.example.practise1Auth',
  );
}
